# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf733b3e4a2288fb5b5266230392c214d2dd14cb377dc941511206a83eee484b1686408a575bcd689b08c2d366d2a681cfd57be9b3716ece2a4c41d10ecafc1f

test:
  secret_key_base: ff8702173442a32973cc7c633a0ba52096aaad30cc4bb59a4bc899b414922e33448767650b12168775440206afa85d715a8d5c306558297e0e9e417486877d55

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
